data:
  raw_data_path: 'data/raw/'
  processed_data_path: 'data/processed/'

model:
  type: 'random_forest'
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42

prediction:
  real_time_data_source: 'api/transit'
  forecast_horizon: 24

server:
  api_host: '0.0.0.0'
  api_port: 5000
  logging_level: 'INFO'
